language: java
jdk:
- oraclejdk8
before_script:
- git submodule update --init
- cd dev/web
deploy:
  provider: heroku
  api_key: d157f6c2-517b-45e7-8345-02900dc310f6
  app: labs-simple-java-be
  on:
    repo: fanky10/labs-simple-java-be
